---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.ts"
exclude_paths:
- node_modules/
- tests/
- "**.js"
- "**.json"
- bin/
- "**.swift"
- "**.xml"