---
engines:
  tslint:
    enabled: true
ratings:
  paths:
  - "**.ts"
exclude_paths:
- node_modules/
- tests/
- bin/
- coverage/
- typings/
- .idea/
- "**.js"
- "**.json"
- "**.swift"
- "**.xml"
- "**.md"