matrix:
  include:
    - os: linux
      language: node_js
      node_js: "6"
    - os: osx
      osx_image: xcode8
      language: objective-c
env: 
- NODE_VERSION="6"
addons:
  code_climate:
    repo_token: 786c6e2d6de4f43ab281eb2660a0ae3c977a993e675bdef839d59c04ea6147a3
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap caskroom/cask; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install java; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install nvm; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gradle; fi
install: 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then nvm install $NODE_VERSION; fi
  - "node --version"
  - "npm install"
  - "npm install -g nyc"
  - "nyc npm test"
  - "npm run build-wrappers"
  - "npm run build-input-project"
  - "npm install -g codecov"
  - "npm install -g codeclimate-test-reporter"
  - "npm run create-code-coverage"
  - "npm run upload-code-coverage"
  - "npm run codacy"
  - "npm install -g gulp"
#  - "cd wiki && mvn clean package && java -cp target/Wiki-1.0-SNAPSHOT.jar io.xrails.App && rm -rf compiler.wiki/ && git clone https://github.com/crossrails/compiler.wiki.git && mv wiki.md compiler.wiki/compiler-options.md && ./deploy.sh "
  - "gulp run-java-tests"
#  - "gulp gen-markdown"
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then set -o pipefail && xcodebuild -project tests/swift/swift.xcodeproj -scheme src build test | xcpretty; fi
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/6ccaf0c916c1b3bfe8a5
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
