env: NODE_VERSION="6"
addons:
  code_climate:
    repo_token: 786c6e2d6de4f43ab281eb2660a0ae3c977a993e675bdef839d59c04ea6147a3
install: 
  - "rm -rf ~/.nvm"
  - "git clone https://github.com/creationix/nvm.git ~/.nvm"
  - "source ~/.nvm/nvm.sh"
  - "nvm install $NODE_VERSION"
  - "node --version"
  - "npm install"
  - "npm install -g nyc"
  - "nyc npm test"
  - "npm run build-wrappers"
  - "npm run build-input-project"
  - "npm install -g codecov"
  - "npm install -g codeclimate-test-reporter"
  - "npm run create-code-coverage"
  - "npm run upload-code-coverage"
language: objective-c
osx_image: xcode8
xcode_project: tests/swift/swift.xcodeproj
xcode_scheme: src
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/6ccaf0c916c1b3bfe8a5
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false