env: NODE_VERSION="6"
addons:
  code_climate:
    repo_token: 786c6e2d6de4f43ab281eb2660a0ae3c977a993e675bdef839d59c04ea6147a3
before_install:
  - brew update
  - brew tap caskroom/cask
  - brew install brew-cask
  - brew cask install java
  - brew install nvm
  - brew install gradle
install: 
  - "nvm install $NODE_VERSION"
  - "node --version"
  - "npm install"
  - "npm install -g nyc"
  - "nyc npm test"
  - "npm run build-wrappers"
  - "npm run build-input-project"
  - "npm install -g codecov"
  - "npm install -g codeclimate-test-reporter"
  - "npm run create-code-coverage"
  - "npm run upload-code-coverage"
  - "cd tests/java/ && gradle test && cd .. && cd .."
language: objective-c
osx_image: xcode7.3
script:
  - set -o pipefail && xcodebuild -project tests/swift/swift.xcodeproj -scheme src build test | xcpretty
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/6ccaf0c916c1b3bfe8a5
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false