version: 0.2.0.{build}
init:
  - git config --global user.name "crossrailsReed" 
  - git config --global user.email crossrails@andrewreed.co.uk 
environment:
  nodejs_version: "6"
  GithubUsername: crossrailsReed
  GithubPassword:
    secure: /iINJgMX9wdzkWxX0ARRYg==
# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - ps: Install-PackageProvider Chocolatey
  # install modules
  - npm install
  - choco install gradle
  - choco install maven
  - cmd: SET PATH=C:\tools\apache-maven-3.3.9\bin;%PATH%
  - ps: refreshenv
# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - mvn --version
  - npm install -g nyc
  - nyc npm test
  - npm run build-wrappers
  - npm run build-input-project
  - npm install -g gulp
  - gradle --version
  - gulp run-java-tests
  #- cd wiki && mvn clean package && java -cp target/Wiki-1.0-SNAPSHOT.jar io.xrails.App && rm -rf compiler.wiki/ && git clone https://github.com/crossrails/compiler.wiki.git && mv wiki.md compiler.wiki/compiler-options.md && cd compiler.wiki/ && git add compiler-options.md && git commit -m "updated wiki" && git push
  - cd wiki 
  - mvn clean package 
  - java -cp target/Wiki-1.0-SNAPSHOT.jar io.xrails.App 
  - cd ..
# Don't actually build.
on_success:
  - cmd: git clone -b gh-pages https://%GithubUsername%:%GithubPassword%@github.com/crossrails/compiler.git pages
  - cmd: cd pages
  - mv ../wiki/wiki.md compiler-options.md
  - git add compiler-options.md 
  - git commit -m "updated wiki" 
  - if [-n "$(git status --porcelain)"](then git push origin gi-pages)
build: off
