# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Crossrails Compiler
email: nbransby@gmail.com
description: > # Crossrails lets you share code between the web and native apps, reducing your cost and time-to-market. Define elegant APIs in TypeScript which are compiled to Java and Swift by the Crossrails compiler. Build your shared library on modern HTML5 APIs such as Fetch, IndexedDB and WebSockets.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.crossrails.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
